### ISSUE TITLE
Share virus related tools

### ISSUE THREAD

**Issue by Miachol** [Miachol/BioInstaller#15]
Configuration file: nongithub.toml
Description: HGT-ID: an efficient and sensitive workflow to detect human-viral insertion sites using next-generation sequencing data

```toml
[hgtid]
source_url = "http://bioinfo.rjh.com.cn/download/bioinstaller/hgtid/{{version}}"
version_available = ["HGT-ID_v1.0.tar.gz", "sampleResults.zip"]
```
